# build_mode_objective_index.py
# FUT.GG RAW objectives -> mode/poster index builder
#
# Purpose
# - Read objectives_raw_latest.json generated by futgg_raw_objective_crawler.py.
# - Do NOT translate or fully parse objectives.
# - Add stable mode flags and poster-inclusion buckets so ChatGPT/manual review can
#   create compact, mode-specific mission route posters.
#
# GitHub Actions example:
#   python -u build_mode_objective_index.py --in outputs/objectives_raw_latest.json --out outputs
#
# Requirements:
#   pandas openpyxl

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

KST = timezone(timedelta(hours=9))

EXCLUDE_MISSION_RE = re.compile(
    r"(Daily Objectives|YouTube|Twitch|FC Pro|eCL Finals|Squad Building Mastery|Assist Mastery|Rush Mastery|Moments Stars Mastery)",
    re.I,
)

EXCLUDE_TEXT_RE = re.compile(
    r"(Link your EA Account|Link your EA account|Watch .*Broadcast|Broadcasts will go live|Complete Moments challenges|Complete .*SBC|Squad Building Challenge groups|Complete Rush Bonuses|Earn [0-9,]+ points by completing bonuses in Rush)",
    re.I,
)

COMPLETIONIST_RE = re.compile(
    r"Complete the .* Objective(?:s)?(?: [0-9]+ times?| [0-9]+ time)?\.?$|Completionist|Complete .* Objectives to earn",
    re.I,
)

ACTION_RE = re.compile(r"^(Play|Win|Score|Assist|Keep|Concede|Complete|Earn|Build|Link|Watch|Claim)", re.I)


def clean_text(x: Any) -> str:
    return re.sub(r"\s+", " ", str(x or "")).strip()


def load_raw_json(path: Path) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def mode_flags(text: str, mode_raw: str, objective_type: str, mission_name: str) -> Dict[str, str]:
    """
    Conservative mode tagging.
    - Any Ultimate Team mode is marked separately and treated as compatible with Core 4 modes for poster source.
    - Custom live-event names are marked as Live Events if objective_type or wording says Live/Event/Exhibition.
    """
    hay = " ".join([clean_text(text), clean_text(mode_raw), clean_text(objective_type), clean_text(mission_name)])

    sb = bool(re.search(r"Squad Battles", hay, re.I))
    rivals = bool(re.search(r"\bRivals\b", hay, re.I))
    champions = bool(re.search(r"\bChampions\b", hay, re.I))
    live = bool(re.search(r"Live Events?|Live Event|Exhibition event|Prime Heroes Event|Visa Event|Path to Glory Live Event|Journey of Nations", hay, re.I)) or objective_type.lower() == "live events"
    rush = bool(re.search(r"\bRush\b", hay, re.I))
    any_ut = bool(re.search(r"any Ultimate Team|Ultimate Team game mode|any mode\b|any Ultimate Team Game Mode", hay, re.I))

    if re.search(r"\(or\s*Rivals/Champions/Live Events\)", hay, re.I) or re.search(r"\(or\s*Live Events/Rivals/Champions\)", hay, re.I):
        sb = rivals = champions = live = True

    if re.search(r"\(or\s*Rush/Rivals/Champions/Live Events\)", hay, re.I) or re.search(r"\(or\s*Rivals/Champions/Live Events/Rush\)", hay, re.I):
        sb = rivals = champions = live = rush = True

    return {
        "allow_squad_battles": "Yes" if sb else "No",
        "allow_rivals": "Yes" if rivals else "No",
        "allow_champions": "Yes" if champions else "No",
        "allow_live_events": "Yes" if live else "No",
        "allow_rush": "Yes" if rush else "No",
        "allow_any_ut": "Yes" if any_ut else "No",
    }


def objective_action_type(text: str) -> str:
    t = clean_text(text)
    if re.search(r"\bAssist\b|through ball|cross", t, re.I):
        return "Assist"
    if re.search(r"\bScore\b|goal|Finesse|Power Shot|header|headed|free kick|Low driven", t, re.I):
        return "Goal"
    if re.search(r"\bWin\b", t, re.I):
        return "Win"
    if re.search(r"\bPlay\b", t, re.I):
        return "Play"
    if re.search(r"Clean Sheet|Concede", t, re.I):
        return "Defense"
    return "Other"


def is_meaningful_gameplay(text: str) -> bool:
    t = clean_text(text)
    if not t:
        return False
    if not ACTION_RE.search(t):
        return False
    if EXCLUDE_TEXT_RE.search(t):
        return False
    if COMPLETIONIST_RE.search(t) and not re.search(r"Play|Win|Score|Assist|Concede|Clean Sheet", t, re.I):
        return False
    return True


def poster_decision(
    mission_name: str,
    objective_type: str,
    text: str,
    flags: Dict[str, str],
    is_new: str,
    only_new: bool,
) -> Tuple[str, str, str, str]:
    """
    Returns: poster_include, poster_bucket, poster_priority, exclude_reason
    """
    mn = clean_text(mission_name)
    t = clean_text(text)
    is_new_yes = str(is_new).strip().lower() == "yes"

    if only_new and not is_new_yes:
        return "No", "Excluded", "90", "신규 목표가 아님"

    if EXCLUDE_MISSION_RE.search(mn):
        return "No", "Excluded", "80", "계정연동/시청/마스터리/장기누적 또는 포스터 비핵심"

    if not is_meaningful_gameplay(t):
        return "No", "Excluded", "70", "설명문/완료 보상/비경기성 목표"

    core_4 = any(flags[k] == "Yes" for k in ["allow_squad_battles", "allow_rivals", "allow_champions", "allow_live_events"])
    any_ut = flags["allow_any_ut"] == "Yes"
    rush = flags["allow_rush"] == "Yes"

    if core_4:
        # Live-event-only is separated because it cannot always be stacked with SB/Rivals/Champions.
        if flags["allow_live_events"] == "Yes" and not any(flags[k] == "Yes" for k in ["allow_squad_battles", "allow_rivals", "allow_champions"]) and not any_ut:
            return "Yes", "Live_Events_Only", "20", ""
        return "Yes", "Core_4_Modes", "10", ""

    if any_ut:
        return "Yes", "Any_UT_Compatible", "15", ""

    if rush:
        return "Yes", "Rush", "30", ""

    return "No", "Excluded", "60", "핵심 4모드/Any UT/Rush 대상 아님"


def row_from_objective(mission: Dict[str, Any], obj: Dict[str, Any], only_new: bool) -> Dict[str, Any]:
    mission_name = clean_text(mission.get("mission_group_name"))
    objective_type = clean_text(mission.get("objective_type"))
    text = clean_text(obj.get("text_raw"))
    mode_raw = clean_text(obj.get("mode_raw"))
    flags = mode_flags(text, mode_raw, objective_type, mission_name)
    include, bucket, priority, reason = poster_decision(
        mission_name=mission_name,
        objective_type=objective_type,
        text=text,
        flags=flags,
        is_new=clean_text(obj.get("is_new")),
        only_new=only_new,
    )

    return {
        "Mission_Group_Name": mission_name,
        "Objective_Type": objective_type,
        "URL": clean_text(mission.get("url")),
        "Campaign_Deadline_KST": clean_text(mission.get("campaign_deadline_kst")),
        "Is_New_Group": clean_text(mission.get("is_new_group")),
        "New_Objective_Count": int(mission.get("new_objective_count") or 0),
        "Objective_Order": int(obj.get("order") or 0),
        "Objective_Name_Raw": clean_text(obj.get("name_raw")),
        "Objective_Text_Raw": text,
        "Reward_Text_Raw": clean_text(obj.get("reward_raw")),
        "Mode_Text_Raw": mode_raw,
        "Difficulty_Text_Raw": clean_text(obj.get("difficulty_raw")),
        "Is_New": clean_text(obj.get("is_new")),
        "Action_Type": objective_action_type(text),
        **flags,
        "Poster_Include": include,
        "Poster_Bucket": bucket,
        "Poster_Priority": priority,
        "Exclude_Reason": reason,
        "Objective_Key": clean_text(obj.get("objective_key")),
    }


def build_rows(raw: Dict[str, Any], only_new: bool) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []
    for mission in raw.get("missions", []):
        for obj in mission.get("objectives", []):
            rows.append(row_from_objective(mission, obj, only_new=only_new))
    return pd.DataFrame(rows)


def build_summary(df: pd.DataFrame, raw: Dict[str, Any], only_new: bool) -> pd.DataFrame:
    manifest = raw.get("manifest", {})
    items = [
        ("Generated_At_KST", datetime.now(KST).strftime("%Y-%m-%d %H:%M:%S")),
        ("Source_Generated_At_KST", manifest.get("Generated_At_KST", "")),
        ("Source_Mission_Group_Count", manifest.get("Mission_Group_Count", "")),
        ("Source_Objective_Row_Count", manifest.get("Objective_Row_Count", "")),
        ("Source_New_Objective_Count", manifest.get("New_Objective_Count", "")),
        ("Only_New_Filter", "Yes" if only_new else "No"),
        ("Mode_Index_Row_Count", len(df)),
        ("Poster_Include_Count", int((df["Poster_Include"] == "Yes").sum()) if not df.empty else 0),
        ("Core_4_Modes_Count", int((df["Poster_Bucket"] == "Core_4_Modes").sum()) if not df.empty else 0),
        ("Any_UT_Compatible_Count", int((df["Poster_Bucket"] == "Any_UT_Compatible").sum()) if not df.empty else 0),
        ("Live_Events_Only_Count", int((df["Poster_Bucket"] == "Live_Events_Only").sum()) if not df.empty else 0),
        ("Rush_Count", int((df["Poster_Bucket"] == "Rush").sum()) if not df.empty else 0),
        ("Excluded_Count", int((df["Poster_Bucket"] == "Excluded").sum()) if not df.empty else 0),
        ("Purpose", "Mode/poster index. Use Poster_* sheets as source for ChatGPT route optimization and poster creation."),
    ]
    return pd.DataFrame(items, columns=["Item", "Value"])


def mission_summary(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return pd.DataFrame(columns=["Mission_Group_Name", "Poster_Include_Count", "Buckets", "Deadline", "New_Objective_Count", "URL"])
    inc = df[df["Poster_Include"] == "Yes"].copy()
    if inc.empty:
        return pd.DataFrame(columns=["Mission_Group_Name", "Poster_Include_Count", "Buckets", "Deadline", "New_Objective_Count", "URL"])

    rows = []
    for name, g in inc.groupby("Mission_Group_Name", sort=False):
        rows.append({
            "Mission_Group_Name": name,
            "Poster_Include_Count": len(g),
            "Buckets": " / ".join(sorted(set(g["Poster_Bucket"]))),
            "Deadline": next((x for x in g["Campaign_Deadline_KST"].tolist() if clean_text(x)), ""),
            "New_Objective_Count": int(g["New_Objective_Count"].max() or 0),
            "URL": g["URL"].iloc[0],
        })
    return pd.DataFrame(rows)


def make_json_payload(df_summary: pd.DataFrame, df: pd.DataFrame) -> Dict[str, Any]:
    source_rows = []
    for _, r in df[df["Poster_Include"] == "Yes"].iterrows():
        out = {}
        for k, v in r.to_dict().items():
            if pd.isna(v):
                out[k.lower()] = ""
            elif isinstance(v, (int, float)) and float(v).is_integer():
                out[k.lower()] = int(v)
            else:
                out[k.lower()] = clean_text(v)
        source_rows.append(out)
    return {
        "summary": {str(r["Item"]): r["Value"] for _, r in df_summary.iterrows()},
        "poster_source_rows": source_rows,
    }


def format_workbook(path: Path):
    wb = load_workbook(path)
    header_fill = PatternFill("solid", fgColor="102A56")
    header_font = Font(color="FFFFFF", bold=True)
    yes_fill = PatternFill("solid", fgColor="E2F0D9")
    excluded_fill = PatternFill("solid", fgColor="F2F2F2")
    new_fill = PatternFill("solid", fgColor="FFF2CC")
    thin = Side(style="thin", color="D9EAF7")

    default_widths = {
        "A": 46, "B": 14, "C": 64, "D": 18, "E": 12, "F": 18, "G": 12, "H": 30,
        "I": 92, "J": 46, "K": 36, "L": 18, "M": 10, "N": 14,
        "O": 18, "P": 12, "Q": 12, "R": 12, "S": 14, "T": 10, "U": 10,
        "V": 14, "W": 20, "X": 12, "Y": 42, "Z": 64
    }

    widths = {
        "Summary": {"A": 32, "B": 100},
        "Mission_Summary": {"A": 48, "B": 18, "C": 32, "D": 16, "E": 18, "F": 64},
    }

    for ws in wb.worksheets:
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = ws.dimensions
        for cell in ws[1]:
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        header = [c.value for c in ws[1]]
        poster_col = header.index("Poster_Include") + 1 if "Poster_Include" in header else None
        new_col = header.index("Is_New") + 1 if "Is_New" in header else None
        for row in ws.iter_rows(min_row=2):
            include_val = clean_text(ws.cell(row[0].row, poster_col).value) if poster_col else ""
            new_val = clean_text(ws.cell(row[0].row, new_col).value) if new_col else ""
            for cell in row:
                cell.alignment = Alignment(vertical="top", wrap_text=True)
                cell.border = Border(top=thin, bottom=thin, left=thin, right=thin)
                if include_val == "Yes":
                    cell.fill = yes_fill
                elif include_val == "No":
                    cell.fill = excluded_fill
                if new_val == "Yes":
                    cell.fill = new_fill
        for col, width in widths.get(ws.title, default_widths).items():
            ws.column_dimensions[col].width = width
    wb.save(path)


def write_outputs(out_dir: Path, df: pd.DataFrame, raw: Dict[str, Any], only_new: bool) -> Tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(KST).strftime("%Y%m%d_%H%M%S")
    xlsx_path = out_dir / f"objectives_mode_index_{timestamp}.xlsx"
    json_path = out_dir / f"objectives_mode_index_{timestamp}.json"

    df_summary = build_summary(df, raw, only_new=only_new)
    df_mission_summary = mission_summary(df)

    sheets = {
        "Summary": df_summary,
        "Mission_Summary": df_mission_summary,
        "Objective_Mode_Index": df,
        "Poster_Core_4Modes": df[df["Poster_Bucket"] == "Core_4_Modes"].copy(),
        "Poster_Any_UT": df[df["Poster_Bucket"] == "Any_UT_Compatible"].copy(),
        "Poster_LiveEvents": df[df["Poster_Bucket"] == "Live_Events_Only"].copy(),
        "Poster_Rush": df[df["Poster_Bucket"] == "Rush"].copy(),
        "Poster_Source_All": df[df["Poster_Include"] == "Yes"].copy(),
        "Excluded": df[df["Poster_Include"] == "No"].copy(),
    }

    with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
        for sheet, data in sheets.items():
            data.to_excel(writer, sheet_name=sheet[:31], index=False)

    format_workbook(xlsx_path)

    payload = make_json_payload(df_summary, df)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    latest_xlsx = out_dir / "objectives_mode_index_latest.xlsx"
    latest_json = out_dir / "objectives_mode_index_latest.json"
    latest_xlsx.write_bytes(xlsx_path.read_bytes())
    latest_json.write_text(json_path.read_text(encoding="utf-8"), encoding="utf-8")

    return xlsx_path, json_path


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build mode/poster index from FUT.GG raw objectives JSON")
    parser.add_argument("--in", dest="input", default="outputs/objectives_raw_latest.json", help="Input raw JSON path")
    parser.add_argument("--out", dest="out", default="outputs", help="Output directory")
    parser.add_argument("--all", action="store_true", help="Include all current gameplay objectives, not only new objectives")
    return parser.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)
    input_path = Path(args.input).expanduser().resolve()
    out_dir = Path(args.out).expanduser().resolve()

    if not input_path.exists():
        raise FileNotFoundError(f"Input raw JSON not found: {input_path}")

    raw = load_raw_json(input_path)
    only_new = not args.all
    df = build_rows(raw, only_new=only_new)

    if not df.empty:
        df["_include_sort"] = df["Poster_Include"].map({"Yes": 0, "No": 1}).fillna(9)
        df["_priority_sort"] = pd.to_numeric(df["Poster_Priority"], errors="coerce").fillna(99)
        df = df.sort_values(["_include_sort", "_priority_sort", "Mission_Group_Name", "Objective_Order"]).drop(columns=["_include_sort", "_priority_sort"])

    xlsx_path, json_path = write_outputs(out_dir, df, raw, only_new=only_new)

    print(f"Mode index XLSX: {xlsx_path}")
    print(f"Mode index JSON: {json_path}")
    print(f"Latest XLSX copy: {out_dir / 'objectives_mode_index_latest.xlsx'}")
    print(f"Latest JSON copy: {out_dir / 'objectives_mode_index_latest.json'}")
    print(f"Rows: {len(df)} | Poster include: {int((df['Poster_Include'] == 'Yes').sum()) if not df.empty else 0} | Only new: {'Yes' if only_new else 'No'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
